//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatsonTruckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Health
    {
        public int GroupHealthInsurance_id { get; set; }
        public int Employee_id { get; set; }
        public string InsuranceCarrier { get; set; }
        public string PolicyNumber { get; set; }
        public string GroupName { get; set; }
        public string IMSGroupNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string ReasonForGrpCoverageRefusal { get; set; }
        public string OtherCoverage { get; set; }
        public string OtherReason { get; set; }
        public string Myself { get; set; }
        public string Spouse { get; set; }
        public string Dependent { get; set; }
        public string OtherInsuranceCoverage { get; set; }
        public Nullable<System.DateTime> CafeteriaPlanYear { get; set; }
        public string NoMedicalPlan { get; set; }
        public string MECPlan { get; set; }
        public string StandardPlan { get; set; }
        public string BuyUpPlan { get; set; }
        public string GrpHRefusalEmpSignature { get; set; }
        public Nullable<System.DateTime> GrpHRefusalEmpSignatureDate { get; set; }
        public string GrpHEnrollmentEmpSignature { get; set; }
        public Nullable<System.DateTime> GrpHEnrollmentEmpSignatureDate { get; set; }
        public string AuthorizationFormPolicyHolderSignature { get; set; }
        public Nullable<System.DateTime> AuthorizationFormPolicyHolderSignatureDate { get; set; }
        public string NameOfPersonOneReleaseInfoTo { get; set; }
        public string PersonOneRelationship { get; set; }
        public string PersonOneSignature { get; set; }
        public Nullable<System.DateTime> PersonOneSignatureDate { get; set; }
        public string NameOfPersonTwoReleaseInfoTo { get; set; }
        public string PersonTwoRelationship { get; set; }
        public string PersonTwoSignature { get; set; }
        public Nullable<System.DateTime> PersonTwoSignatureDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
