//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatsonTruckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsurancePlan()
        {
            this.InsurancePlanDetails = new HashSet<InsurancePlanDetail>();
            this.InsurancePremiums = new HashSet<InsurancePremium>();
        }
    
        public int InsurancePlan_id { get; set; }
        public int Employee_id { get; set; }
        public string MECPlan { get; set; }
        public string StandardPlan { get; set; }
        public string BuyUpPlan { get; set; }
        public string DentalPlan { get; set; }
        public string VisionPlan { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePlanDetail> InsurancePlanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePremium> InsurancePremiums { get; set; }
    }
}
