//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatsonTruckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePremium
    {
        public int InsurancePremium_id { get; set; }
        public int InsurancePlan_id { get; set; }
        public string EmployeeOnly { get; set; }
        public string EmployeeAndSpouse { get; set; }
        public string EmployeeAndDependent { get; set; }
        public string EmployeeAndFamily { get; set; }
        public Nullable<decimal> YearlyPremiumCost { get; set; }
        public Nullable<decimal> MonthlyPremiumCost { get; set; }
        public Nullable<decimal> BiWeeklyPremiumCost { get; set; }
    
        public virtual InsurancePlan InsurancePlan { get; set; }
    }
}
