//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatsonTruckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicant
    {
        public int JobApplicant_id { get; set; }
        public int Employee_id { get; set; }
        public string PositionApplyingFor { get; set; }
        public Nullable<System.DateTime> StartDateAvailability { get; set; }
        public string ApplicantSignature { get; set; }
        public Nullable<System.DateTime> ApplicantSignatureDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SSN { get; set; }
        public string Address { get; set; }
        public string PObox { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string YearsResidedAtPresentAddr { get; set; }
        public string PreviousAddress { get; set; }
        public string PreviousPObox { get; set; }
        public string PreviousCity { get; set; }
        public string PreviousState { get; set; }
        public string PreviousZipCode { get; set; }
        public string YearsResidedAtPreviousAddr { get; set; }
        public string OverEighteen { get; set; }
        public string Age { get; set; }
        public string PreviouslyEmployedAtWatson { get; set; }
        public Nullable<System.DateTime> EmploymentDatesAtWatsonFrom { get; set; }
        public Nullable<System.DateTime> EmploymentDatesAtWatsonTo { get; set; }
        public string Veteran { get; set; }
        public string MOSorSpecializedTraining { get; set; }
        public string DriversLicense { get; set; }
        public string LicenseState { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> LicenseExpirationDate { get; set; }
        public string PhoneNumber { get; set; }
        public string ElementaryInstitution { get; set; }
        public string YearsCompletedElementary { get; set; }
        public string FieldOfStudyElementary { get; set; }
        public string GraduateElementary { get; set; }
        public string HighSchoolInstitution { get; set; }
        public string YearsCompletedHighSchool { get; set; }
        public string FieldOfStudyHighSchool { get; set; }
        public string GraduateHighSchool { get; set; }
        public string CollegeInstitution { get; set; }
        public string YearsCompletedCollege { get; set; }
        public string FieldOfStudyCollege { get; set; }
        public string GraduateOrDegreeCollege { get; set; }
        public string TechnicalInstitution { get; set; }
        public string YearsCompletedTechnical { get; set; }
        public string FieldOfStudyTechnical { get; set; }
        public string GraduateOrDegreeTechnical { get; set; }
        public string AdditionalInstitution { get; set; }
        public string YearsCompletedAtAdditional { get; set; }
        public string FieldOfStudyAtAdditional { get; set; }
        public string GraduateOrDegreeAtAdditional { get; set; }
        public string PresentOrLastEmployer { get; set; }
        public string EmployerPhoneNumber { get; set; }
        public string EmployerAddress { get; set; }
        public string EmployerPObox { get; set; }
        public string EmployerCity { get; set; }
        public string EmployerState { get; set; }
        public string EmployerZipCode { get; set; }
        public Nullable<System.DateTime> EmployedFromDate { get; set; }
        public Nullable<System.DateTime> EmployedToDate { get; set; }
        public string TitleOfPositionHeld { get; set; }
        public string TypeOfWorkedPerformed { get; set; }
        public string NameOfSupervisor { get; set; }
        public string PresentOrLastEmployerTwo { get; set; }
        public string EmployerPhoneNumberTwo { get; set; }
        public string EmployerAddressTwo { get; set; }
        public string EmployerPOboxTwo { get; set; }
        public string EmployerCityTwo { get; set; }
        public string EmployerStateTwo { get; set; }
        public string EmployerZipCodeTwo { get; set; }
        public Nullable<System.DateTime> EmployedFromDateTwo { get; set; }
        public Nullable<System.DateTime> EmployedToDateTwo { get; set; }
        public string TitleOfPositionHeldTwo { get; set; }
        public string TypeOfWorkedPerformedTwo { get; set; }
        public string NameOfSupervisorTwo { get; set; }
        public string PresentOrLastEmployerThree { get; set; }
        public string EmployerPhoneNumberThree { get; set; }
        public string EmployerAddressThree { get; set; }
        public string EmployerPOboxThree { get; set; }
        public string EmployerCityThree { get; set; }
        public string EmployerStateThree { get; set; }
        public string EmployerZipCodeThree { get; set; }
        public Nullable<System.DateTime> EmployedFromDateThree { get; set; }
        public Nullable<System.DateTime> EmployedToDateThree { get; set; }
        public string TitleOfPositionHeldThree { get; set; }
        public string TypeOfWorkedPerformedThree { get; set; }
        public string NameOfSupervisorThree { get; set; }
        public string TerminatedOrResigned { get; set; }
        public string ReasonForTerminationOrResignation { get; set; }
        public string ReasonForEmploymentGaps { get; set; }
        public string ReferenceFirstName { get; set; }
        public string ReferenceLastName { get; set; }
        public string ReferencePhoneNumber { get; set; }
        public string ReferenceAddress { get; set; }
        public string ReferencePObox { get; set; }
        public string ReferenceCity { get; set; }
        public string ReferenceState { get; set; }
        public string ReferenceZipCode { get; set; }
        public string ReferenceOccupation { get; set; }
        public string YearsKnownReference { get; set; }
        public string ReferenceFirstNameTwo { get; set; }
        public string ReferenceLastNameTwo { get; set; }
        public string ReferenceAddressTwo { get; set; }
        public string ReferencePOboxTwo { get; set; }
        public string ReferenceCityTwo { get; set; }
        public string ReferenceStateTwo { get; set; }
        public string ReferenceZipCodeTwo { get; set; }
        public string ReferenceOccupationTwo { get; set; }
        public string YearsKnownReferenceTwo { get; set; }
        public string ReferencePhoneNumberTwo { get; set; }
        public string ReferenceFirstNameThree { get; set; }
        public string ReferenceLastNameThree { get; set; }
        public string ReferenceAddressThree { get; set; }
        public string ReferencePOboxThree { get; set; }
        public string ReferenceCityThree { get; set; }
        public string ReferenceStateThree { get; set; }
        public string ReferenceZipCodeThree { get; set; }
        public string ReferenceOccupationThree { get; set; }
        public string YearsKnownReferenceThree { get; set; }
        public string ReferencePhoneNumberThree { get; set; }
        public string Experience { get; set; }
        public string ListOtherExperience { get; set; }
        public string Certification { get; set; }
        public string ApplicantSignatureTwo { get; set; }
        public Nullable<System.DateTime> ApplicantSignatureDateTwo { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
