//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatsonTruckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int Vacation_id { get; set; }
        public int Employee_id { get; set; }
        public int VactionRemaining { get; set; }
        public int SickLeave { get; set; }
        public int PTO { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
